services:
  - type: web
    name: nexthire-ai-backend
    env: node
    rootDir: server
    buildCommand: "npm install"
    startCommand: "node src/server.js"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: GOOGLE_API_KEY
        sync: false  # ONLY THIS ONE IS NEEDED

staticSites:
  - name: nexthire-ai-frontend
    rootDir: client
    buildCommand: "npm install && npm run build"
    publishDir: "dist"
    envVars:
      - key: VITE_API_URL
        sync: false
